# fly.toml app configuration file generated for film-lightbox-proud-moon-8455 on 2026-04-30T21:57:29+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'film-light-box'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
